modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="sun_panels"
version="1.0.0"
displayName="Simplest Solar Panels"
authors="TeamSolar"
description='''
A simple mod that adds three tiers of solar panels to Minecraft.

Basic Solar Panel:
- Power Output: 32 RF/t
- Internal Storage: 4,000 RF

Advanced Solar Panel:
- Power Output: 128 RF/t
- Internal Storage: 16,000 RF

Elite Solar Panel:
- Power Output: 512 RF/t
- Internal Storage: 64,000 RF
'''

[[dependencies.sun_panels]]
modId="neoforge"
type="required"
versionRange="[20.4.0-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.sun_panels]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"